apiVersion: apps/v1
kind: Deployment
metadata:
  name: query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: cloudpoc.azurecr.io/query:v1
          ports:
            - containerPort: 8083
---
kind: Service
apiVersion: v1
metadata:
  # Name of our service
  name: cloud-poc-service-Query
spec:
  # LoadBalancer type to allow external access to multiple ports
  type: LoadBalancer
  selector:
    # Will deliver external traffic to the pod holding each of our containers
    app: query
  ports:
    #- name: sentiment
      #protocol: TCP
     - port: 8083
      #targetPort: containerport